# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plexsphere.models.bridge_ingress_rule_update_request import BridgeIngressRuleUpdateRequest

class TestBridgeIngressRuleUpdateRequest(unittest.TestCase):
    """BridgeIngressRuleUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BridgeIngressRuleUpdateRequest:
        """Test BridgeIngressRuleUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BridgeIngressRuleUpdateRequest`
        """
        model = BridgeIngressRuleUpdateRequest()
        if include_optional:
            return BridgeIngressRuleUpdateRequest(
                sni_host = 'gWzyBAw2ZuufUOHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCD.W.k.bUofvKERjsmInY9s-EmMH6kw8gsnXv2Z7jRPK542XGp8ZoM.Eb-ziKqEde8fXg9wdpfxa2-zRi2iAxU4NCUavTrirUe4ba7d.2.i.g.GE-ArE6U3CZ-Vnrj9RmauFxv71lRsCjOv6MeuvKGSDRGKUIQh.u.IoEdbZpGptfI4pvLXGuLk-kwwO2jcMEEkIauW5ApNat.E.6LaR2kw9-zmvqRnM-dar09VaHCQz0TlT4b42Jml4PJXMbVMO8G0e5q9Zw.iovY63Gk6ixTd5NxRU25mQYd6Vi.EkQ5H9-FH2v5iUaMQ6iIJT.LxDSR-lIIfhhw9bP3XhsKpT6YkX2ymMVYtYsFBx8OyxaBZ75cAidDh.6.S.L.HRdyiJF6.v.x.H.w.BV3VP-DPQpzY-c9WhD1h649MeAEDz67NR.ShNlL1YPO1GvRUm.WR0-Ssway.r.wONPZw-HU.dfykpn8.G.s.j.Y.7.u.rNn1oLFWRpST.y6.IYhZAGiUmDTPB5iVX1lhmY7Gh2I3pT2Sm.G.5.b.7.k6RQusWUzrY2IaluFJfz8Zwx6YGC1.JndVdQ8Zqh8o9Fu3-luW1PzrlptgIbB7lMjnQXJdim087U4e00u0',
                target_node_id = '',
                target_port = 1,
                acme_account_ref = ''
            )
        else:
            return BridgeIngressRuleUpdateRequest(
                sni_host = 'gWzyBAw2ZuufUOHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCD.W.k.bUofvKERjsmInY9s-EmMH6kw8gsnXv2Z7jRPK542XGp8ZoM.Eb-ziKqEde8fXg9wdpfxa2-zRi2iAxU4NCUavTrirUe4ba7d.2.i.g.GE-ArE6U3CZ-Vnrj9RmauFxv71lRsCjOv6MeuvKGSDRGKUIQh.u.IoEdbZpGptfI4pvLXGuLk-kwwO2jcMEEkIauW5ApNat.E.6LaR2kw9-zmvqRnM-dar09VaHCQz0TlT4b42Jml4PJXMbVMO8G0e5q9Zw.iovY63Gk6ixTd5NxRU25mQYd6Vi.EkQ5H9-FH2v5iUaMQ6iIJT.LxDSR-lIIfhhw9bP3XhsKpT6YkX2ymMVYtYsFBx8OyxaBZ75cAidDh.6.S.L.HRdyiJF6.v.x.H.w.BV3VP-DPQpzY-c9WhD1h649MeAEDz67NR.ShNlL1YPO1GvRUm.WR0-Ssway.r.wONPZw-HU.dfykpn8.G.s.j.Y.7.u.rNn1oLFWRpST.y6.IYhZAGiUmDTPB5iVX1lhmY7Gh2I3pT2Sm.G.5.b.7.k6RQusWUzrY2IaluFJfz8Zwx6YGC1.JndVdQ8Zqh8o9Fu3-luW1PzrlptgIbB7lMjnQXJdim087U4e00u0',
                target_node_id = '',
                target_port = 1,
        )
        """

    def testBridgeIngressRuleUpdateRequest(self):
        """Test BridgeIngressRuleUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
