# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plexsphere.models.domain_reachability_policy import DomainReachabilityPolicy

class TestDomainReachabilityPolicy(unittest.TestCase):
    """DomainReachabilityPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainReachabilityPolicy:
        """Test DomainReachabilityPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainReachabilityPolicy`
        """
        model = DomainReachabilityPolicy()
        if include_optional:
            return DomainReachabilityPolicy(
                heartbeat_interval = '30s',
                stale_after = '90s',
                unreachable_after = '300s'
            )
        else:
            return DomainReachabilityPolicy(
                heartbeat_interval = '30s',
                stale_after = '90s',
                unreachable_after = '300s',
        )
        """

    def testDomainReachabilityPolicy(self):
        """Test DomainReachabilityPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
