# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plexsphere.models.node_state_policy import NodeStatePolicy

class TestNodeStatePolicy(unittest.TestCase):
    """NodeStatePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeStatePolicy:
        """Test NodeStatePolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeStatePolicy`
        """
        model = NodeStatePolicy()
        if include_optional:
            return NodeStatePolicy(
                revision_id = '',
                fingerprint = 'YQ==',
                rules = [
                    plexsphere.models.node_state_compiled_rule.NodeStateCompiledRule(
                        action = 'allow', 
                        protocol = 'tcp', 
                        source_cidr = '', 
                        destination_cidr = '', 
                        ports = plexsphere.models.policy_port_range.PolicyPortRange(
                            from = 1, 
                            to = 1, ), )
                    ]
            )
        else:
            return NodeStatePolicy(
                revision_id = '',
                fingerprint = 'YQ==',
                rules = [
                    plexsphere.models.node_state_compiled_rule.NodeStateCompiledRule(
                        action = 'allow', 
                        protocol = 'tcp', 
                        source_cidr = '', 
                        destination_cidr = '', 
                        ports = plexsphere.models.policy_port_range.PolicyPortRange(
                            from = 1, 
                            to = 1, ), )
                    ],
        )
        """

    def testNodeStatePolicy(self):
        """Test NodeStatePolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
