"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "plexsphere-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="plexsphere API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "plexsphere API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="BUSL-1.1",
    long_description_content_type='text/markdown',
    long_description="""\
    HTTP contract for plexsphere&#39;s meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated &#x60;/v1/*&#x60; request (&#x60;POST&#x60;, &#x60;PATCH&#x60;, &#x60;PUT&#x60;, &#x60;DELETE&#x60;) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the &#x60;plexsphere_csrf&#x60; cookie value in the &#x60;X-Plexsphere-CSRF&#x60; header. Violations surface as &#x60;403 application/problem+json&#x60; with &#x60;code&#x60; ∈ { &#x60;csrf-token-mismatch&#x60;, &#x60;csrf-origin-mismatch&#x60;, &#x60;csrf-origin-not-configured&#x60; }. Bearer-authenticated requests (&#x60;Authorization: Bearer …&#x60;) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (&#x60;/v1/auth/*&#x60;) is exempt because it cannot carry a Principal yet. 
    """,  # noqa: E501
    package_data={"plexsphere": ["py.typed"]},
)
