# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApprovalKind(str, Enum):
    """
    Source family the queue row was projected from. `approval` marks a dual-control Approval raised against a Domain `ApprovalPolicy`; `credential_assignment` marks a Credential Assignment awaiting a decision on the Cloud Credential it spends; `cloud_assignment` marks a Cloud Assignment awaiting a decision on the Cloud it spends. The kind selects which per-row authorisation check and which decide path apply. 
    """

    """
    allowed enum values
    """
    APPROVAL = 'approval'
    CREDENTIAL_ASSIGNMENT = 'credential_assignment'
    CLOUD_ASSIGNMENT = 'cloud_assignment'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApprovalKind from a JSON string"""
        return cls(json.loads(json_str))


