# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GroupRequest(BaseModel):
    """
    Body for POST /v1/admin/groups. Field set mirrors the `Group` aggregate. DECISION: the aggregate enforces a source-specific invariant at construction time — `source=idp` requires both `idp_binding_id` (non-zero) AND `idp_claim_value` (non-empty); `source=manual` forbids both. Violations are rejected with a 400 Problem from validation rather than by a SQL CHECK constraint, so the failure surfaces in the transport layer rather than the persistence layer. 
    """ # noqa: E501
    domain_id: UUID = Field(description="Owning Domain.")
    slug: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(description="URL-safe identifier unique within `domain_id`. Lowercase ASCII letters, digits, and internal dashes only; cannot start or end with a dash. ")
    display_name: Annotated[str, Field(strict=True, max_length=128)] = Field(description="Human-friendly Group name.")
    source: StrictStr = Field(description="Provenance of the Group. `manual` means the Group was created via this admin API; `idp` means it is reconciled from an IdP claim. DECISION: `source=idp` requires `idp_binding_id` and `idp_claim_value`; `source=manual` forbids both. The aggregate rejects mismatches so the error surfaces as 400, not as a SQL CHECK violation . ")
    idp_binding_id: Optional[UUID] = Field(default=None, description="IdP binding the Group is reconciled from. Required when `source=idp`; must be omitted when `source=manual` . ")
    idp_claim_value: Optional[StrictStr] = Field(default=None, description="Verbatim IdP claim value the Group reconciles to. Required when `source=idp`; must be omitted when `source=manual` . ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["domain_id", "slug", "display_name", "source", "idp_binding_id", "idp_claim_value"]

    @field_validator('slug')
    def slug_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z0-9]([a-z0-9-]{0,62}[a-z0-9])?$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]([a-z0-9-]{0,62}[a-z0-9])?$/")
        return value

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['manual', 'idp']):
            raise ValueError("must be one of enum values ('manual', 'idp')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain_id": obj.get("domain_id"),
            "slug": obj.get("slug"),
            "display_name": obj.get("display_name"),
            "source": obj.get("source"),
            "idp_binding_id": obj.get("idp_binding_id"),
            "idp_claim_value": obj.get("idp_claim_value")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


