# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HeartbeatRequest(BaseModel):
    """
    Body for POST /v1/nodes/{id}/heartbeat. Carries the per-Node liveness signal plexd emits at a 30s cadence: the client wall-clock (for skew detection), the SHA-256 of the running plexd binary (for tamper-evidence and rollout tracking), the human-readable plexd version string, and a free-form NAT summary that the controller correlates with the per-Domain bridge view in later stories. 
    """ # noqa: E501
    client_now: datetime = Field(description="Client wall-clock timestamp at the moment the heartbeat was assembled. The handler rejects the request with 400 `clock_skew` if the value drifts more than 60 seconds from server now. ")
    binary_checksum: Union[Annotated[bytes, Field(min_length=32, strict=True, max_length=64)], Annotated[str, Field(min_length=32, strict=True, max_length=64)]] = Field(description="SHA-256 digest of the running plexd binary. The wire form is the 32-byte raw digest encoded as either lowercase hex (64 characters) or base64 with standard padding (44 characters); the handler decodes both forms and rejects anything else with 400 `binary_checksum_empty`. ")
    binary_version: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Human-readable plexd version string (e.g. `plexd-v0.4.2-ge5f3a1c`). Non-empty per the application- boundary invariants — the handler rejects an empty value with 400 `binary_version_empty`. ")
    nat_summary: Dict[str, Any] = Field(description="Free-form NAT discovery summary produced by plexd. Empty object is permitted — later stories define the schema once the per-Domain bridge orchestrator lands . ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["client_now", "binary_checksum", "binary_version", "nat_summary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HeartbeatRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HeartbeatRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "client_now": obj.get("client_now"),
            "binary_checksum": obj.get("binary_checksum"),
            "binary_version": obj.get("binary_version"),
            "nat_summary": obj.get("nat_summary")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


