# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.incident_severity import IncidentSeverity
from plexsphere.models.incident_status import IncidentStatus
from plexsphere.models.timeline_event import TimelineEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Incident(BaseModel):
    """
    A per-Domain operational incident with its append-only timeline. A resolved incident carries a `resolved_at` timestamp; an open incident does not. 
    """ # noqa: E501
    id: UUID = Field(description="Stable identifier of the incident (UUIDv7).")
    domain_id: UUID = Field(description="Domain the incident is scoped to.")
    title: Annotated[str, Field(strict=True, max_length=200)] = Field(description="Short human-readable title of the incident.")
    severity: IncidentSeverity
    status: IncidentStatus
    opened_at: datetime = Field(description="RFC 3339 instant the incident was opened.")
    resolved_at: Optional[datetime] = Field(default=None, description="RFC 3339 instant the incident was resolved, or absent while it is still open. ")
    timeline: List[TimelineEvent] = Field(description="The incident's append-only timeline, ordered by `occurred_at` ascending. The list projection omits the timeline; the single-incident read includes it. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "domain_id", "title", "severity", "status", "opened_at", "resolved_at", "timeline"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Incident from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in timeline (list)
        _items = []
        if self.timeline:
            for _item_timeline in self.timeline:
                if _item_timeline:
                    _items.append(_item_timeline.to_dict())
            _dict['timeline'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Incident from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "domain_id": obj.get("domain_id"),
            "title": obj.get("title"),
            "severity": obj.get("severity"),
            "status": obj.get("status"),
            "opened_at": obj.get("opened_at"),
            "resolved_at": obj.get("resolved_at"),
            "timeline": [TimelineEvent.from_dict(_item) for _item in obj["timeline"]] if obj.get("timeline") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


