# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from plexsphere.models.integrity_violation_kind import IntegrityViolationKind
from plexsphere.models.integrity_violation_status import IntegrityViolationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntegrityViolationRow(BaseModel):
    """
    One integrity-violation row returned by `ListIntegrityViolations` — a metadata-only projection scoped to the owning Domain. 
    """ # noqa: E501
    id: UUID = Field(description="Integrity-violation identifier (UUIDv7).")
    node_id: UUID = Field(description="Node that reported the violation (UUIDv7).")
    domain_id: UUID = Field(description="Owning Domain (UUIDv7) — the residency pivot the per-row visibility filter authorises against. ")
    kind: IntegrityViolationKind
    status: IntegrityViolationStatus
    artifact_id: StrictStr = Field(description="Stable identifier of the affected artifact (hook name, binary path label, or host-key file label). ")
    detected_at: datetime = Field(description="Timestamp the agent detected the violation (UTC).")
    acknowledged_at: Optional[datetime] = Field(default=None, description="Timestamp an operator acknowledged the violation (UTC). `null` or omitted while the violation is still `open`. ")
    acknowledged_by_subject: Optional[StrictStr] = Field(default=None, description="Subject string of the operator that acknowledged the violation. `null` or omitted while the violation is still `open`. ")
    acknowledge_reason: Optional[StrictStr] = Field(default=None, description="Free-text rationale recorded with the acknowledgement. `null` or omitted while the violation is still `open`. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "node_id", "domain_id", "kind", "status", "artifact_id", "detected_at", "acknowledged_at", "acknowledged_by_subject", "acknowledge_reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrityViolationRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrityViolationRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "node_id": obj.get("node_id"),
            "domain_id": obj.get("domain_id"),
            "kind": obj.get("kind"),
            "status": obj.get("status"),
            "artifact_id": obj.get("artifact_id"),
            "detected_at": obj.get("detected_at"),
            "acknowledged_at": obj.get("acknowledged_at"),
            "acknowledged_by_subject": obj.get("acknowledged_by_subject"),
            "acknowledge_reason": obj.get("acknowledge_reason")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


