# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntegrityViolationRequest(BaseModel):
    """
    Single integrity-violation report inside an `IntegrityViolationsRequest`. The `kind` field discriminates between the three artifact classes the agent monitors. For `binary_checksum` and `hook_checksum` the entry carries the observed and (optionally) expected 32-byte SHA-256 digests; for `ssh_host_key` it carries the observed and (optionally) expected `SHA256:<base64>` fingerprints. Cross-kind column leakage (a `binary_checksum` carrying a fingerprint, or an `ssh_host_key` carrying a checksum) is rejected with 400 `integrity_violation_kind_mismatch`. 
    """ # noqa: E501
    kind: StrictStr = Field(description="Artifact class the divergence applies to. A value outside this closed set is rejected with 400 `integrity_violation_kind_invalid`. ")
    detected_by: StrictStr = Field(description="On-Node detector that surfaced the violation: the agent's startup self-check, an inotify-triggered re-check during normal operation, or a pre-dispatch verification before running a hook. A value outside this closed set is rejected with 400 `integrity_violation_detected_by_invalid`. ")
    artifact_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Stable identifier of the affected artifact (hook name, binary path label, or host-key file label). Non-empty after trimming whitespace; a violation surfaces as 400 `integrity_violation_artifact_id_empty`. ")
    observed_checksum: Optional[Union[StrictBytes, StrictStr]] = Field(default=None, description="SHA-256 digest the agent observed for the artifact, 32 bytes base64-encoded with standard padding. REQUIRED for the `binary_checksum` and `hook_checksum` kinds; MUST be empty or absent for the `ssh_host_key` kind. Anything that does not decode to exactly 32 bytes (when expected) is rejected with 400 `integrity_violation_checksum_invalid`. A non-empty value on an `ssh_host_key` entry surfaces as 400 `integrity_violation_kind_mismatch`. ")
    expected_checksum: Optional[Union[StrictBytes, StrictStr]] = Field(default=None, description="Optional SHA-256 digest the agent expected for the artifact, 32 bytes base64-encoded. Accepted only for the `binary_checksum` and `hook_checksum` kinds. When present, anything that does not decode to exactly 32 bytes is rejected with 400 `integrity_violation_checksum_invalid`. ")
    observed_fingerprint: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="OpenSSH SHA-256 host-key fingerprint the agent observed, rendered as `SHA256:<base64>`. REQUIRED for the `ssh_host_key` kind; MUST be empty or absent for the checksum kinds. A non-empty value on a checksum kind surfaces as 400 `integrity_violation_kind_mismatch`; a value that does not match the canonical form surfaces as 400 `integrity_violation_host_key_fingerprint_invalid`. ")
    expected_fingerprint: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Optional OpenSSH SHA-256 host-key fingerprint the agent expected, rendered as `SHA256:<base64>`. Accepted only for the `ssh_host_key` kind. A value that does not match the canonical form is rejected with 400 `integrity_violation_host_key_fingerprint_invalid`. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["kind", "detected_by", "artifact_id", "observed_checksum", "expected_checksum", "observed_fingerprint", "expected_fingerprint"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['binary_checksum', 'hook_checksum', 'ssh_host_key']):
            raise ValueError("must be one of enum values ('binary_checksum', 'hook_checksum', 'ssh_host_key')")
        return value

    @field_validator('detected_by')
    def detected_by_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['startup_scan', 'inotify', 'pre_dispatch']):
            raise ValueError("must be one of enum values ('startup_scan', 'inotify', 'pre_dispatch')")
        return value

    @field_validator('observed_fingerprint')
    def observed_fingerprint_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^SHA256:[A-Za-z0-9+\/]+={0,2}$", value):
            raise ValueError(r"must validate the regular expression /^SHA256:[A-Za-z0-9+\/]+={0,2}$/")
        return value

    @field_validator('expected_fingerprint')
    def expected_fingerprint_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^SHA256:[A-Za-z0-9+\/]+={0,2}$", value):
            raise ValueError(r"must validate the regular expression /^SHA256:[A-Za-z0-9+\/]+={0,2}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrityViolationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrityViolationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "detected_by": obj.get("detected_by"),
            "artifact_id": obj.get("artifact_id"),
            "observed_checksum": obj.get("observed_checksum"),
            "expected_checksum": obj.get("expected_checksum"),
            "observed_fingerprint": obj.get("observed_fingerprint"),
            "expected_fingerprint": obj.get("expected_fingerprint")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


