# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from plexsphere.models.invitation_initial_tuple import InvitationInitialTuple
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvitationCreateRequest(BaseModel):
    """
    Body for `POST /v1/domains/{id}/invitations`. The handler authorises the call against the parent Domain's `manage` ReBAC relation BEFORE invoking the service so an unauthorised caller never produces an `InvitationCreated` outbox row. The plaintext `external_subject` is intentionally NOT echoed in the response — only the per-Domain pseudonym is — so a server-side log of the response body never carries raw IdP-side PII. 
    """ # noqa: E501
    external_subject: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="IdP-side subject identifier (typically the OIDC `sub` claim or operator-known login name) the invitation is staged for. Whitespace-only is rejected by the aggregate . ")
    ttl_seconds: Optional[Annotated[int, Field(le=604800, strict=True, ge=60)]] = Field(default=86400, description="Lifetime of the invitation in seconds, applied to `created_at` to derive `expires_at`. Out-of-range values surface as `400 invalid_ttl`. Defaults to 86400 (24h); ceiling is 7 days. ")
    initial_tuples: Optional[Annotated[List[InvitationInitialTuple], Field(max_length=32)]] = Field(default=None, description="Optional bounded list (max 32) of relation tuples to write into SpiceDB atomically when the invitation is accepted. Exceeding the cap surfaces as `422 too_many_initial_tuples`. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["external_subject", "ttl_seconds", "initial_tuples"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvitationCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in initial_tuples (list)
        _items = []
        if self.initial_tuples:
            for _item_initial_tuples in self.initial_tuples:
                if _item_initial_tuples:
                    _items.append(_item_initial_tuples.to_dict())
            _dict['initial_tuples'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvitationCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_subject": obj.get("external_subject"),
            "ttl_seconds": obj.get("ttl_seconds") if obj.get("ttl_seconds") is not None else 86400,
            "initial_tuples": [InvitationInitialTuple.from_dict(_item) for _item in obj["initial_tuples"]] if obj.get("initial_tuples") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


