# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvitationInitialTuple(BaseModel):
    """
    Relation tuple consumed atomically when an Invitation is accepted. The aggregate stores the tuples as a bounded jsonb array (max 32) on `plexsphere.invitations.initial_tuples` and rejects entries whose `object` is not in the closed prefix set `{domain:<this-id>, project:<uuid>, group:<uuid>}` — cross- Domain or platform-scoped objects surface as `422 invitation_object_out_of_scope`. The aggregate also rejects a non-JSON-encodable `caveat_context` with `422 invalid_caveat_context`. 
    """ # noqa: E501
    relation: Annotated[str, Field(min_length=1, strict=True)] = Field(description="SpiceDB relation the tuple grants on `object` (e.g. `member`, `viewer`). Whitespace-only is rejected by the aggregate. ")
    object: Annotated[str, Field(min_length=1, strict=True)] = Field(description="SpiceDB object reference the tuple targets. Allowed prefix set is closed: `domain:<this-domain-id>`, `project:<uuid>`, or `group:<uuid>`. The handler validates the prefix BEFORE the aggregate constructor so an out-of- scope object surfaces as `422 invitation_object_out_of_scope` rather than a generic `invalid_body`. ")
    caveat_context: Optional[Dict[str, Any]] = Field(default=None, description="Optional CEL caveat context forwarded verbatim to SpiceDB on accept. The aggregate enforces JSON-encodable lossless round-trip — a value that fails the round-trip surfaces as `422 invalid_caveat_context`. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["relation", "object", "caveat_context"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvitationInitialTuple from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvitationInitialTuple from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "relation": obj.get("relation"),
            "object": obj.get("object"),
            "caveat_context": obj.get("caveat_context")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


