# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.label_value_schema import LabelValueSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LabelDefinitionRequest(BaseModel):
    """
    Body for POST /v1/label-definitions. Mirrors the DDD `CreateDefinitionParams` shape: the caller names the scope as a discriminator + optional UUID, the local key, and the value contract. The services layer performs the `manage` ReBAC check on the scope-object before persisting. 
    """ # noqa: E501
    scope: StrictStr = Field(description="Scope discriminator.")
    scope_id: Optional[UUID] = Field(default=None, description="Tenancy identifier. Required when `scope` is `domain` or `project`; omitted when `scope=platform`. ")
    local_key: StrictStr = Field(description="Unqualified key token — lowercase letters, digits, `.`, `_`, `-`; 1–64 characters; no leading or trailing separator. ")
    description: Optional[Annotated[str, Field(strict=True, max_length=512)]] = None
    value_schema: LabelValueSchema
    applicable_kinds: Annotated[List[StrictStr], Field(min_length=1)]
    required: Optional[StrictBool] = Field(default=None, description="When `true`, Assignments of this Definition are mandatory on every object of the applicable kinds. ")
    default_value: Optional[Any] = None
    immutable: Optional[StrictBool] = None
    cloud_tag_propagation: Optional[StrictBool] = None
    on_delete: Optional[StrictStr] = Field(default=None, description="On-delete policy. Defaults to `block` when omitted . ")
    cardinality: Optional[StrictInt] = Field(default=None, description="Declared per-object cardinality cap for Assignments of this Definition. Defaults to `1` when omitted . ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["scope", "scope_id", "local_key", "description", "value_schema", "applicable_kinds", "required", "default_value", "immutable", "cloud_tag_propagation", "on_delete", "cardinality"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['platform', 'domain', 'project']):
            raise ValueError("must be one of enum values ('platform', 'domain', 'project')")
        return value

    @field_validator('on_delete')
    def on_delete_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['block', 'cascade', 'orphan']):
            raise ValueError("must be one of enum values ('block', 'cascade', 'orphan')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabelDefinitionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value_schema
        if self.value_schema:
            _dict['value_schema'] = self.value_schema.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if default_value (nullable) is None
        # and model_fields_set contains the field
        if self.default_value is None and "default_value" in self.model_fields_set:
            _dict['default_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabelDefinitionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scope": obj.get("scope"),
            "scope_id": obj.get("scope_id"),
            "local_key": obj.get("local_key"),
            "description": obj.get("description"),
            "value_schema": LabelValueSchema.from_dict(obj["value_schema"]) if obj.get("value_schema") is not None else None,
            "applicable_kinds": obj.get("applicable_kinds"),
            "required": obj.get("required"),
            "default_value": obj.get("default_value"),
            "immutable": obj.get("immutable"),
            "cloud_tag_propagation": obj.get("cloud_tag_propagation"),
            "on_delete": obj.get("on_delete"),
            "cardinality": obj.get("cardinality")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


