# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from plexsphere.models.node_state_bridge_ingress import NodeStateBridgeIngress
from plexsphere.models.node_state_bridge_relay import NodeStateBridgeRelay
from plexsphere.models.node_state_bridge_site_to_site import NodeStateBridgeSiteToSite
from plexsphere.models.node_state_bridge_user_access import NodeStateBridgeUserAccess
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodeStateBridge(BaseModel):
    """
    Per-Node bridge-orchestrator delivered-config block. Carries the relay configuration, the user-access providers, the public ingress rules, and the site-to-site tunnels the addressed Node must program. Each child block is present-but-nullable so plexd's reconcile loop can diff by field presence. 
    """ # noqa: E501
    relay: Optional[NodeStateBridgeRelay] = Field(default=None, description="Relay configuration the Node must program. `null` when no relay is configured on the owning bridge Resource. ")
    user_access: Optional[NodeStateBridgeUserAccess] = Field(default=None, description="User-access providers the Node must program. `null` when the owning bridge Resource defines none. ")
    ingress: Optional[NodeStateBridgeIngress] = Field(default=None, description="Public-ingress rules the Node must program. `null` when the owning bridge Resource defines none. ")
    site_to_site: Optional[NodeStateBridgeSiteToSite] = Field(default=None, description="Site-to-site tunnels the Node must program. `null` when the owning bridge Resource defines none. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["relay", "user_access", "ingress", "site_to_site"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeStateBridge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of relay
        if self.relay:
            _dict['relay'] = self.relay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_access
        if self.user_access:
            _dict['user_access'] = self.user_access.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ingress
        if self.ingress:
            _dict['ingress'] = self.ingress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of site_to_site
        if self.site_to_site:
            _dict['site_to_site'] = self.site_to_site.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeStateBridge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "relay": NodeStateBridgeRelay.from_dict(obj["relay"]) if obj.get("relay") is not None else None,
            "user_access": NodeStateBridgeUserAccess.from_dict(obj["user_access"]) if obj.get("user_access") is not None else None,
            "ingress": NodeStateBridgeIngress.from_dict(obj["ingress"]) if obj.get("ingress") is not None else None,
            "site_to_site": NodeStateBridgeSiteToSite.from_dict(obj["site_to_site"]) if obj.get("site_to_site") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


