# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from plexsphere.models.policy_action import PolicyAction
from plexsphere.models.policy_port_range import PolicyPortRange
from plexsphere.models.policy_protocol import PolicyProtocol
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodeStateCompiledRule(BaseModel):
    """
    Single canonicalised L3/L4 rule the controller projected for the addressed Node. The five-tuple `(source_cidr, destination_cidr, protocol, ports, action)` mirrors `PolicyRule` so plexd's reconcile loop can reuse the same rule programmer regardless of whether the rule came from the operator-facing Policy aggregate or the compiled fan-out. `ports` MUST be omitted for `icmp` and `any` and MUST be populated for `tcp` and `udp` — the protocol/port coherence check is enforced at the policy aggregate boundary, so a compiled rule that reaches the wire is guaranteed coherent. 
    """ # noqa: E501
    action: PolicyAction
    protocol: PolicyProtocol
    source_cidr: StrictStr = Field(description="IPv4 or IPv6 prefix in CIDR notation (e.g. `10.0.0.0/8`, `2001:db8::/32`). Source and destination agree on address family by aggregate-boundary invariant. ")
    destination_cidr: StrictStr = Field(description="IPv4 or IPv6 prefix in CIDR notation. Address family matches `source_cidr`. ")
    ports: Optional[PolicyPortRange] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["action", "protocol", "source_cidr", "destination_cidr", "ports"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeStateCompiledRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ports
        if self.ports:
            _dict['ports'] = self.ports.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeStateCompiledRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "protocol": obj.get("protocol"),
            "source_cidr": obj.get("source_cidr"),
            "destination_cidr": obj.get("destination_cidr"),
            "ports": PolicyPortRange.from_dict(obj["ports"]) if obj.get("ports") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


