# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.node_state_compiled_rule import NodeStateCompiledRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodeStatePolicy(BaseModel):
    """
    Per-Node compiled policy fan-out block. Carries the merged rule list the controller projected for the addressed Node, the base64-encoded SHA-256 fingerprint that plexd uses to short-circuit reconcile when the locally-applied ruleset already matches, and the revision identifier of the policy-id-ascending first matched Policy. The block is `null` on the `NodeStateSnapshot` envelope when no compiled ruleset row exists for the addressed Node (the per-Node selector did not match any active Policy revision).  Multi-policy semantics: the controller persists one `plexsphere.policy_compiled_ruleset` row per (Node, Policy) tuple. When a Node matches multiple Policies, the snapshot composer merges those rows by sorting on `policy_id` and concatenating each row's `rule_payload` bytes in ascending order. `rules` decodes the merged byte stream into the canonical wire shape; `fingerprint` is `sha256.Sum256(payload_0 || payload_1 || ...)` over the same byte stream; `revision_id` is drawn from the policy-id-ascending first row so a single uuid remains on the wire. Plexd treats the fingerprint as an opaque comparison key — it is stable for a given (Node, set of matched Policy revisions, rule_payload byte streams) tuple and changes whenever any contributing row changes. 
    """ # noqa: E501
    revision_id: UUID = Field(description="Identifier of the Policy revision the merged ruleset anchors on — drawn from the policy-id-ascending first row when the addressed Node matches multiple Policies. A Node matching a single Policy carries that Policy's revision id directly. ")
    fingerprint: Union[Annotated[bytes, Field(min_length=44, strict=True, max_length=44)], Annotated[str, Field(min_length=44, strict=True, max_length=44)]] = Field(description="SHA-256 digest over the merged `rule_payload` byte stream the controller persisted in `plexsphere.policy_compiled_ruleset`. Exactly 32 bytes once decoded; on the wire the field is base64-encoded with standard padding (44 ASCII characters). For a Node matching a single Policy the digest equals `sha256.Sum256(rule_payload)`; for a Node matching multiple Policies it equals `sha256.Sum256(payload_0 || payload_1 || ...)` with `payload_i` ordered by ascending `policy_id`. The digest is an opaque comparison key — plexd compares it byte-for-byte against its locally-applied ruleset's stored digest and does not re-derive it from the `rules` array. ")
    rules: List[NodeStateCompiledRule] = Field(description="Canonical, deterministically-sorted L3/L4 rule list the addressed Node MUST program. For multi-policy matches the array is the per-Policy concatenation of each row's canonical rule list in policy-id-ascending order. Empty array is a legitimate state — it means the Node matches at least one Policy's selector pair but no Policy contributed any rules (or every rule was filtered out). ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["revision_id", "fingerprint", "rules"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeStatePolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeStatePolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "revision_id": obj.get("revision_id"),
            "fingerprint": obj.get("fingerprint"),
            "rules": [NodeStateCompiledRule.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


