# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ObjectSearchRequest(BaseModel):
    """
    Body for POST /v1/objects/search. Names the Label selector to resolve, the tenancy scope to resolve it within, and the ReBAC relation each match is access-checked against. 
    """ # noqa: E501
    selector: Annotated[str, Field(min_length=1, strict=True, max_length=4096)] = Field(description="Raw label-selector expression (for example `env=production, tier in (gold, silver)`). Parsed by the same grammar /v1/labels/selectors/preview validates. ")
    relation: Annotated[str, Field(min_length=1, strict=True, max_length=4096)] = Field(description="ReBAC relation the caller must hold on a match for it to appear in the result (for example `read`). Required; clients commonly default it to `read`. ")
    scope: StrictStr = Field(description="Tenancy universe the selector is resolved within. `platform` spans every object; `domain` and `project` narrow the match set to objects carrying at least one in-scope Label. ")
    scope_id: Optional[UUID] = Field(default=None, description="Domain or Project UUID addressed by `scope`. Required when `scope` is `domain` or `project`; MUST be omitted (or the zero UUID) when `scope` is `platform`. ")
    kind: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Optional object-kind filter (for example `project` or `node`). When set, only matches of that kind are returned; when omitted the result is mixed-kind. ")
    cursor: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Opaque forward cursor from a previous page's `next_cursor`. Omit (or send empty) to read the first page. ")
    limit: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Upper bound on the PRE-filter page size. Because the ReBAC filter runs after pagination, the returned page may hold fewer items than `limit`; paginate until `next_cursor` is absent. Omitted defers to the server default. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["selector", "relation", "scope", "scope_id", "kind", "cursor", "limit"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['platform', 'domain', 'project']):
            raise ValueError("must be one of enum values ('platform', 'domain', 'project')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "selector": obj.get("selector"),
            "relation": obj.get("relation"),
            "scope": obj.get("scope"),
            "scope_id": obj.get("scope_id"),
            "kind": obj.get("kind"),
            "cursor": obj.get("cursor"),
            "limit": obj.get("limit")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


