# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from plexsphere.models.policy_diff_pair import PolicyDiffPair
from plexsphere.models.policy_rule import PolicyRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolicyDiff(BaseModel):
    """
    Structural difference between two canonicalised Policy rule lists. Canonicalisation sorts the list into a deterministic order so a reorder-only edit produces empty `added`, `removed`, and `modified` arrays. 
    """ # noqa: E501
    added: List[PolicyRule] = Field(description="Rules present in the target revision but not the source.")
    removed: List[PolicyRule] = Field(description="Rules present in the source revision but not the target.")
    modified: List[PolicyDiffPair] = Field(description="Rules sharing a stable key on both sides where only the `action` field differs. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["added", "removed", "modified"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyDiff from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in added (list)
        _items = []
        if self.added:
            for _item_added in self.added:
                if _item_added:
                    _items.append(_item_added.to_dict())
            _dict['added'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in removed (list)
        _items = []
        if self.removed:
            for _item_removed in self.removed:
                if _item_removed:
                    _items.append(_item_removed.to_dict())
            _dict['removed'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in modified (list)
        _items = []
        if self.modified:
            for _item_modified in self.modified:
                if _item_modified:
                    _items.append(_item_modified.to_dict())
            _dict['modified'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyDiff from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "added": [PolicyRule.from_dict(_item) for _item in obj["added"]] if obj.get("added") is not None else None,
            "removed": [PolicyRule.from_dict(_item) for _item in obj["removed"]] if obj.get("removed") is not None else None,
            "modified": [PolicyDiffPair.from_dict(_item) for _item in obj["modified"]] if obj.get("modified") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


