# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from plexsphere.models.namespace_phase import NamespacePhase
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectClusterAssignmentResponse(BaseModel):
    """
    Read-side projection of a Project ↔ management-cluster assignment. The shape is shared by `GetProjectManagementClusterAssignment`, `ListManagementClusterAssignments`, and `TerminateProjectManagementClusterAssignment`. 
    """ # noqa: E501
    project_id: UUID = Field(description="Placed Project identifier (UUIDv7).")
    management_cluster_id: UUID = Field(description="Identifier of the management cluster the Project is placed onto. ")
    region: StrictStr = Field(description="Region the assignment landed in.")
    namespace_name: StrictStr = Field(description="Derived per-Project namespace name on the management cluster (`plexsphere-project-<project-uuid>`). ")
    namespace_phase: NamespacePhase
    assigned_at: datetime = Field(description="Assignment creation timestamp (UTC).")
    updated_at: datetime = Field(description="Last-modified timestamp (UTC); bumped on every phase advance. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["project_id", "management_cluster_id", "region", "namespace_name", "namespace_phase", "assigned_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectClusterAssignmentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectClusterAssignmentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "management_cluster_id": obj.get("management_cluster_id"),
            "region": obj.get("region"),
            "namespace_name": obj.get("namespace_name"),
            "namespace_phase": obj.get("namespace_phase"),
            "assigned_at": obj.get("assigned_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


