# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProvisionedResourcePhase(str, Enum):
    """
    Closed-set lifecycle phase of a broker-owned ProvisionedResource. `Pending` is the entry phase set when the broker accepts a provisioning declaration; the reconcile loop drives the aggregate forward through `Provisioning` and `Enrolling` to the terminal `Ready` or `Failed`. `Deregistering` and `Deprovisioning` are teardown phases entered when an operator deletes the parent Resource; `Deleted` is the post-teardown terminal. 
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    PROVISIONING = 'Provisioning'
    ENROLLING = 'Enrolling'
    READY = 'Ready'
    FAILED = 'Failed'
    DEREGISTERING = 'Deregistering'
    DEPROVISIONING = 'Deprovisioning'
    DELETED = 'Deleted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProvisionedResourcePhase from a JSON string"""
        return cls(json.loads(json_str))


