# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from plexsphere.models.cloud_provider import CloudProvider
from plexsphere.models.cloud_provider_package import CloudProviderPackage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProviderBundleCreateRequest(BaseModel):
    """
    Body for `POST /v1/provider-bundles`. The field set mirrors the `ProviderBundle` aggregate's construction invariants. The handler authorises the call against the platform-level `manage` relation BEFORE invoking the service, so an unauthorised caller never produces a `ProviderBundleCreated` outbox row. 
    """ # noqa: E501
    display_name: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Human-readable bundle name. Whitespace-only is rejected.")
    slug: Annotated[str, Field(min_length=1, strict=True, max_length=63)] = Field(description="Kebab-case URL handle. The aggregate's `ParseSlug` enforces the same regex; surfacing the pattern here lets the generated client validate before the round-trip. ")
    provider: CloudProvider
    provider_packages: Annotated[List[CloudProviderPackage], Field(min_length=1, max_length=16)] = Field(description="The Crossplane provider packages the bundle declares. At least one entry is required, and each `source` may appear only once. The read surfaces render the set in canonical source-ascending order, not in the order stated here. ")
    provider_config_api_version: Annotated[str, Field(min_length=3, strict=True, max_length=270)] = Field(description="The `<group>/<version>` every declared package serves its ProviderConfig under (e.g. `aws.m.upbound.io/v1beta1`). ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["display_name", "slug", "provider", "provider_packages", "provider_config_api_version"]

    @field_validator('slug')
    def slug_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]+(-[a-z0-9]+)*$/")
        return value

    @field_validator('provider_config_api_version')
    def provider_config_api_version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\/v[0-9]+((alpha|beta)[0-9]+)?$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\/v[0-9]+((alpha|beta)[0-9]+)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderBundleCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in provider_packages (list)
        _items = []
        if self.provider_packages:
            for _item_provider_packages in self.provider_packages:
                if _item_provider_packages:
                    _items.append(_item_provider_packages.to_dict())
            _dict['provider_packages'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderBundleCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "display_name": obj.get("display_name"),
            "slug": obj.get("slug"),
            "provider": obj.get("provider"),
            "provider_packages": [CloudProviderPackage.from_dict(_item) for _item in obj["provider_packages"]] if obj.get("provider_packages") is not None else None,
            "provider_config_api_version": obj.get("provider_config_api_version")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


