# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.register_peer import RegisterPeer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RegisterResponse(BaseModel):
    """
    Response body for POST /v1/register. Bundles every artifact plexd needs to finish its bootstrap: the freshly-allocated `node_id` + `mesh_ip`, the Domain's signing public key + key id (for SSE event verification), the per-Node NSK plaintext (returned EXACTLY ONCE — see the `x-plexsphere-once: true` marker on the `nsk` field), the initial wireguard peer snapshot for table programming, and the Domain's mesh CIDR for routing-table programming.  Operators MUST capture the `nsk` plaintext from this response and persist it locally on the registering Node — no API surface ever returns it again. The Spectral `plexsphere-write-once-post-must-be-issue-response` rule polices the `x-plexsphere-once: true` marker so the plaintext cannot accidentally appear on any other operation . 
    """ # noqa: E501
    node_id: UUID = Field(description="Freshly-allocated Node aggregate id (UUIDv7). Echoed in the response so plexd records its own identity. ")
    mesh_ip: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Allocator-assigned mesh address inside the Domain's mesh CIDR. Canonical `netip.Addr` string form (`100.64.0.1`, never zero-padded). ")
    signing_public_key: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Domain's active signing public key, base64-encoded. Plexd pins this and uses it to verify signed SSE events delivered. ")
    signing_key_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Identifier (kid) the Domain's active signing key is indexed under (e.g. a DID-URL fragment). Carried so plexd can rotate-aware verify SSE events whose header references a non-current kid during a rotation grace window. ")
    nsk: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Per-Node Node Secret Key plaintext (32 bytes, base64- encoded). **Shown exactly once** — there is no API surface that ever returns the plaintext again because the persistence layer stores only the wrapped form. Operators MUST capture it from this response and pin it on the registering Node out-of-band. The Spectral rule polices this guarantee against any future schema that would leak the marker outside this single response. ")
    peer_snapshot: List[RegisterPeer] = Field(description="Initial wireguard peer set the registering Node needs to bring its table up. Empty for the first Node enrolled into a Domain. Subsequent membership churn is delivered through the SSE stream rather than re-issued here. ")
    domain_mesh_cidr: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Domain's mesh CIDR (e.g. `100.64.0.0/10`). Carried so plexd can program its routing table without a follow-up Domain lookup. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["node_id", "mesh_ip", "signing_public_key", "signing_key_id", "nsk", "peer_snapshot", "domain_mesh_cidr"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegisterResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in peer_snapshot (list)
        _items = []
        if self.peer_snapshot:
            for _item_peer_snapshot in self.peer_snapshot:
                if _item_peer_snapshot:
                    _items.append(_item_peer_snapshot.to_dict())
            _dict['peer_snapshot'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegisterResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "node_id": obj.get("node_id"),
            "mesh_ip": obj.get("mesh_ip"),
            "signing_public_key": obj.get("signing_public_key"),
            "signing_key_id": obj.get("signing_key_id"),
            "nsk": obj.get("nsk"),
            "peer_snapshot": [RegisterPeer.from_dict(_item) for _item in obj["peer_snapshot"]] if obj.get("peer_snapshot") is not None else None,
            "domain_mesh_cidr": obj.get("domain_mesh_cidr")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


