# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SessionActivityTCP(BaseModel):
    """
    TCP session lifecycle activity a Node posts for a `tcp` session. The shape is deliberately payload-blind — exactly a start and an end with byte counters, no L7 interpretation. 
    """ # noqa: E501
    phase: StrictStr = Field(description="Lifecycle phase: `session_started` opens the tunnel, `session_ended` closes it. ")
    target_host: Optional[StrictStr] = Field(default=None, description="Target host the tunnel connected to. Present on `session_started`. ")
    target_port: Optional[StrictInt] = Field(default=None, description="Target port the tunnel connected to. Present on `session_started`. ")
    bytes_in: Optional[StrictInt] = Field(default=None, description="Bytes forwarded from the operator to the target. Present on `session_ended`. ")
    bytes_out: Optional[StrictInt] = Field(default=None, description="Bytes forwarded from the target to the operator. Present on `session_ended`. ")
    terminated_by: Optional[StrictStr] = Field(default=None, description="What closed the tunnel. Present on `session_ended`. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["phase", "target_host", "target_port", "bytes_in", "bytes_out", "terminated_by"]

    @field_validator('phase')
    def phase_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['session_started', 'session_ended']):
            raise ValueError("must be one of enum values ('session_started', 'session_ended')")
        return value

    @field_validator('terminated_by')
    def terminated_by_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ttl_expired', 'idle_timeout', 'plexd_close', 'operator_revoke']):
            raise ValueError("must be one of enum values ('ttl_expired', 'idle_timeout', 'plexd_close', 'operator_revoke')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionActivityTCP from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionActivityTCP from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phase": obj.get("phase"),
            "target_host": obj.get("target_host"),
            "target_port": obj.get("target_port"),
            "bytes_in": obj.get("bytes_in"),
            "bytes_out": obj.get("bytes_out"),
            "terminated_by": obj.get("terminated_by")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


