# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.sink_enablement_state import SinkEnablementState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SinkEnablement(BaseModel):
    """
    One Project's permission to deliver telemetry to one sink of that Project's own Domain. It names the Project, the sink, the lifecycle state, the principal that asked for the grant, and the decision that settled it. 
    """ # noqa: E501
    id: UUID = Field(description="Stable identifier of the enablement (UUIDv7).")
    project_id: UUID = Field(description="Project the grant is filed for.")
    sink_id: UUID = Field(description="Sink the grant addresses.")
    state: SinkEnablementState
    requested_by: UUID = Field(description="Principal that asked for the grant.")
    decided_by_subject: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="ReBAC subject of the principal that moved the enablement out of `requested`. Absent while the enablement is undecided. ")
    decided_at: Optional[datetime] = Field(default=None, description="RFC 3339 timestamp the decision was recorded. Absent while the enablement is undecided. ")
    decision_reason: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Rationale recorded with the decision. A rejection and a revocation both carry one; an approval records none, so the field is absent on an approved enablement. ")
    created_at: datetime = Field(description="RFC 3339 timestamp the enablement was filed.")
    sync_pending: Optional[StrictBool] = Field(default=None, description="Set on a grant response only. `true` means the grant COMMITTED — the row moved and its event is durable — but the arm that mirrors it into the authorization graph has not completed, so the grant is not yet effective. The caller must NOT retry: the retry is refused by the live-unique index and reports a conflict for work that already happened. The committed event drives the same mutation through the authz-sync arm. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "project_id", "sink_id", "state", "requested_by", "decided_by_subject", "decided_at", "decision_reason", "created_at", "sync_pending"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SinkEnablement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SinkEnablement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "sink_id": obj.get("sink_id"),
            "state": obj.get("state"),
            "requested_by": obj.get("requested_by"),
            "decided_by_subject": obj.get("decided_by_subject"),
            "decided_at": obj.get("decided_at"),
            "decision_reason": obj.get("decision_reason"),
            "created_at": obj.get("created_at"),
            "sync_pending": obj.get("sync_pending")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


