# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from plexsphere.models.sink_credential_input import SinkCredentialInput
from plexsphere.models.sink_settings import SinkSettings
from plexsphere.models.sink_tls import SinkTLS
from plexsphere.models.tenant_sink_type import TenantSinkType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SinkUpdateRequest(BaseModel):
    """
    Body for `PUT /v1/sinks/{id}`. It is the full post-image: a mutable field absent from the body is cleared, not left untouched.  `id`, `domain_id` and `built_in` are immutable once the sink exists and are therefore absent from the body; a write that would change any of them is refused with `409 sink_conflict`.  `expected_updated_at` is the compare-and-swap token and is REQUIRED. Because the body replaces the whole sink, a client writing from a stale read silently restores every mutable field it never touched — including `tls.insecure_skip_verify`, `tls.ca_pem` and `credential`. Stating the `updated_at` the client read makes that a `409 sink_cas_conflict` instead. 
    """ # noqa: E501
    expected_updated_at: datetime = Field(description="The `updated_at` the client read the sink at. The write is applied only if the stored sink still carries it; a sink changed since that read is refused with `409 sink_cas_conflict` and nothing is written. ")
    slug: Annotated[str, Field(strict=True, max_length=63)] = Field(description="Kebab-case handle, unique among the Domain's sinks. Moving it onto a slug another sink of the Domain holds is refused with `409 sink_slug_taken`. ")
    display_name: Annotated[str, Field(strict=True, max_length=256)] = Field(description="Human-readable name the sink is listed under.")
    sink_type: TenantSinkType
    endpoint: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="Address to deliver to, valid for the stated type. A host naming a literal address inside the platform's own network is refused. ")
    tls: Optional[SinkTLS] = None
    credential: Optional[SinkCredentialInput] = None
    settings: Optional[SinkSettings] = None
    __properties: ClassVar[List[str]] = ["expected_updated_at", "slug", "display_name", "sink_type", "endpoint", "tls", "credential", "settings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SinkUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tls
        if self.tls:
            _dict['tls'] = self.tls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credential
        if self.credential:
            _dict['credential'] = self.credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SinkUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "expected_updated_at": obj.get("expected_updated_at"),
            "slug": obj.get("slug"),
            "display_name": obj.get("display_name"),
            "sink_type": obj.get("sink_type"),
            "endpoint": obj.get("endpoint"),
            "tls": SinkTLS.from_dict(obj["tls"]) if obj.get("tls") is not None else None,
            "credential": SinkCredentialInput.from_dict(obj["credential"]) if obj.get("credential") is not None else None,
            "settings": SinkSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None
        })
        return _obj


