# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.sink_credential import SinkCredential
from plexsphere.models.sink_settings import SinkSettings
from plexsphere.models.sink_tls import SinkTLS
from plexsphere.models.sink_type import SinkType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Sink(BaseModel):
    """
    One destination a Domain's routing layer may deliver to, either tenant-declared or built in. The two shapes are the same thing to a Telemetry Route: a named destination it may target.  A built-in sink names a platform backend and carries no `domain_id`, no `endpoint`, no `credential` and no `tls`; its slug equals its type. 
    """ # noqa: E501
    id: UUID = Field(description="Stable identifier of the sink (UUIDv7).")
    domain_id: Optional[UUID] = Field(default=None, description="Domain that declared the sink. Absent on a built-in sink, which belongs to no Domain. ")
    slug: Annotated[str, Field(strict=True, max_length=63)] = Field(description="Kebab-case handle the sink is addressed by within its scope — unique per Domain for a tenant sink, globally for a built-in one. ")
    display_name: Annotated[str, Field(strict=True, max_length=256)] = Field(description="Human-readable name the sink is listed under.")
    sink_type: SinkType
    built_in: StrictBool = Field(description="Whether the sink is platform-provided. A built-in sink is reachable from a route without an enablement and is neither updatable nor deletable. ")
    endpoint: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="Address the sink delivers to — a URL or a host and port pair, depending on the type. Empty on a built-in sink, which the platform addresses through its own configuration. ")
    tls: Optional[SinkTLS] = None
    credential: Optional[SinkCredential] = None
    settings: Optional[SinkSettings] = None
    created_at: datetime = Field(description="RFC 3339 timestamp the sink was declared.")
    updated_at: datetime = Field(description="RFC 3339 timestamp the sink was last changed.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "domain_id", "slug", "display_name", "sink_type", "built_in", "endpoint", "tls", "credential", "settings", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sink from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tls
        if self.tls:
            _dict['tls'] = self.tls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credential
        if self.credential:
            _dict['credential'] = self.credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sink from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "domain_id": obj.get("domain_id"),
            "slug": obj.get("slug"),
            "display_name": obj.get("display_name"),
            "sink_type": obj.get("sink_type"),
            "built_in": obj.get("built_in"),
            "endpoint": obj.get("endpoint"),
            "tls": SinkTLS.from_dict(obj["tls"]) if obj.get("tls") is not None else None,
            "credential": SinkCredential.from_dict(obj["credential"]) if obj.get("credential") is not None else None,
            "settings": SinkSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


