# coding: utf-8

"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.telemetry_severity import TelemetrySeverity
from plexsphere.models.telemetry_signal import TelemetrySignal
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TelemetryRouteRequest(BaseModel):
    """
    Body for `POST /v1/projects/{id}/telemetry-routes` and `PUT /v1/telemetry-routes/{id}`. On the update it is the full post-image: a field absent from the body is cleared, not left untouched.  `project_id` is absent from the body because the stored value is immutable — the create takes the Project from the path, and the update applies against the Project the route already belongs to. 
    """ # noqa: E501
    signal: TelemetrySignal
    severity_floor: Optional[TelemetrySeverity] = Field(default=None, description="Least severe log keyword to carry. Stated on a `logs` route only; stating it on another signal is refused with `422 telemetry_route_invalid` rather than carried along and ignored at delivery. ")
    name_prefix: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Leading characters of the metric names to select. Stated on a `metrics` route only; stating it on another signal is refused with `422 telemetry_route_invalid`. ")
    sink_ids: Annotated[List[UUID], Field(min_length=1, max_length=16)] = Field(description="Sinks to deliver to. At least one and at most sixteen, no zero id, and no sink named twice. The ceiling bounds the delivery fan-out a single batch pays for, which the per-Project route limit alone does not. Each target is checked at authoring time, so a route that would deliver nowhere is refused where it is written. ")
    __properties: ClassVar[List[str]] = ["signal", "severity_floor", "name_prefix", "sink_ids"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TelemetryRouteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TelemetryRouteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signal": obj.get("signal"),
            "severity_floor": obj.get("severity_floor"),
            "name_prefix": obj.get("name_prefix"),
            "sink_ids": obj.get("sink_ids")
        })
        return _obj


