"""
    plexsphere API

    HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/*`) is exempt because it cannot carry a Principal yet. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from uuid import UUID
from plexsphere.models.capability_row_list import CapabilityRowList
from plexsphere.models.capability_status import CapabilityStatus

from plexsphere.api_client import ApiClient, RequestSerialized
from plexsphere.api_response import ApiResponse
from plexsphere.rest import RESTResponseType


class CapabilitiesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_capabilities(
        self,
        project_id: Annotated[UUID, Field(description="Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project. ")],
        node_id: Annotated[Optional[UUID], Field(description="Optional Node filter. When present, only the capability row for the named Node is returned. ")] = None,
        status: Annotated[Optional[CapabilityStatus], Field(description="Optional checksum-status filter. When present, only rows in the named status are returned. ")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True, ge=1)]], Field(description="Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CapabilityRowList:
        """List per-Node capability manifests in a Project.

        Returns a cursor-paginated page of per-Node capability rows in the named Project. Each row pairs a Node's reported agent binary with a checksum status — `match` when the reported checksum equals a known-good artifact, `drift` when it differs, and `unknown` when no known-good artifact is on record. The handler runs the platform read gate before the persistence read, then layers a per-row visibility filter on the Domain owning each Node so `items` is the subset the caller is authorised to see.  The pagination cursor is HMAC-signed and bound to the per-(caller, pepper) pseudonym; a cross-caller replay surfaces as `403 cursor_binding_mismatch`, and a tampered or malformed cursor surfaces as `400 invalid_cursor`. `limit` is clamped to `[1, 200]` rather than rejected. 

        :param project_id: Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project.  (required)
        :type project_id: UUID
        :param node_id: Optional Node filter. When present, only the capability row for the named Node is returned. 
        :type node_id: UUID
        :param status: Optional checksum-status filter. When present, only rows in the named status are returned. 
        :type status: CapabilityStatus
        :param cursor: Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. 
        :type cursor: str
        :param limit: Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. 
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_capabilities_serialize(
            project_id=project_id,
            node_id=node_id,
            status=status,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CapabilityRowList",
            '400': "Problem",
            '401': "Problem",
            '403': "PermissionDenied",
            '500': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_capabilities_with_http_info(
        self,
        project_id: Annotated[UUID, Field(description="Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project. ")],
        node_id: Annotated[Optional[UUID], Field(description="Optional Node filter. When present, only the capability row for the named Node is returned. ")] = None,
        status: Annotated[Optional[CapabilityStatus], Field(description="Optional checksum-status filter. When present, only rows in the named status are returned. ")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True, ge=1)]], Field(description="Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CapabilityRowList]:
        """List per-Node capability manifests in a Project.

        Returns a cursor-paginated page of per-Node capability rows in the named Project. Each row pairs a Node's reported agent binary with a checksum status — `match` when the reported checksum equals a known-good artifact, `drift` when it differs, and `unknown` when no known-good artifact is on record. The handler runs the platform read gate before the persistence read, then layers a per-row visibility filter on the Domain owning each Node so `items` is the subset the caller is authorised to see.  The pagination cursor is HMAC-signed and bound to the per-(caller, pepper) pseudonym; a cross-caller replay surfaces as `403 cursor_binding_mismatch`, and a tampered or malformed cursor surfaces as `400 invalid_cursor`. `limit` is clamped to `[1, 200]` rather than rejected. 

        :param project_id: Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project.  (required)
        :type project_id: UUID
        :param node_id: Optional Node filter. When present, only the capability row for the named Node is returned. 
        :type node_id: UUID
        :param status: Optional checksum-status filter. When present, only rows in the named status are returned. 
        :type status: CapabilityStatus
        :param cursor: Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. 
        :type cursor: str
        :param limit: Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. 
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_capabilities_serialize(
            project_id=project_id,
            node_id=node_id,
            status=status,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CapabilityRowList",
            '400': "Problem",
            '401': "Problem",
            '403': "PermissionDenied",
            '500': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_capabilities_without_preload_content(
        self,
        project_id: Annotated[UUID, Field(description="Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project. ")],
        node_id: Annotated[Optional[UUID], Field(description="Optional Node filter. When present, only the capability row for the named Node is returned. ")] = None,
        status: Annotated[Optional[CapabilityStatus], Field(description="Optional checksum-status filter. When present, only rows in the named status are returned. ")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True, ge=1)]], Field(description="Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List per-Node capability manifests in a Project.

        Returns a cursor-paginated page of per-Node capability rows in the named Project. Each row pairs a Node's reported agent binary with a checksum status — `match` when the reported checksum equals a known-good artifact, `drift` when it differs, and `unknown` when no known-good artifact is on record. The handler runs the platform read gate before the persistence read, then layers a per-row visibility filter on the Domain owning each Node so `items` is the subset the caller is authorised to see.  The pagination cursor is HMAC-signed and bound to the per-(caller, pepper) pseudonym; a cross-caller replay surfaces as `403 cursor_binding_mismatch`, and a tampered or malformed cursor surfaces as `400 invalid_cursor`. `limit` is clamped to `[1, 200]` rather than rejected. 

        :param project_id: Owning Project (UUIDv7). The capability inventory is scoped to Nodes in this Project.  (required)
        :type project_id: UUID
        :param node_id: Optional Node filter. When present, only the capability row for the named Node is returned. 
        :type node_id: UUID
        :param status: Optional checksum-status filter. When present, only rows in the named status are returned. 
        :type status: CapabilityStatus
        :param cursor: Opaque continuation token returned by a previous call's `next_cursor`. The encoding is HMAC-signed so a tampered cursor surfaces as `400`. 
        :type cursor: str
        :param limit: Maximum number of items to return in a single page. The handler clamps the value to [1, 200] before forwarding it to the read service. 
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_capabilities_serialize(
            project_id=project_id,
            node_id=node_id,
            status=status,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CapabilityRowList",
            '400': "Problem",
            '401': "Problem",
            '403': "PermissionDenied",
            '500': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_capabilities_serialize(
        self,
        project_id,
        node_id,
        status,
        cursor,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if project_id is not None:
            _path_params['project_id'] = project_id
        # process the query parameters
        if node_id is not None:
            
            _query_params.append(('node_id', node_id))
            
        if status is not None:
            
            _query_params.append(('status', status.value))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/projects/{project_id}/capabilities',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


